export const UPDATE_POST = 'UPDATE_POST';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
